server:
  port: 8080


spring:
  application:
    name: gateway 
  logging:
    level:
      org.springframework.web: INFO
      org.springframework.cloud.gateway: INFO
      reactor.netty.http.server.AccessLog: INFO 
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: account
              uri: http://localhost:8081
              predicates:
                - Path=/api/account/**
              filters:
                - StripPrefix=1
            - id: wallet
              uri: http://localhost:8082
              predicates:
                - Path=/api/wallet/**
              filters:
                - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: health,info